const ar: Record<string, string> = {
  // Day type
  WORKING: 'يوم عمل',
  BEFORE_HOLIDAY: 'قبل العطلة',
  HOLIDAY: 'عطلة',
  AFTER_HOLIDAY: 'بعد العطلة',

  // Accident situation
  ON_ROAD: 'على الطريق',
  ON_SHOULDER: 'على الكتف',
  ON_VERGE: 'على الحافة',
  ON_SIDEWALK: 'على الرصيف',
  ON_BIKE_PATH: 'على مسار الدراجات',
  ON_BIKE_LANE: 'على حارة الدراجات',
  OFF_PLATFORM: 'خارج المنصة',

  // Zone
  ROAD: 'طريق',
  URBAN: 'حضري',
  CROSSING: 'تقاطع',
  BYPASS: 'طريق التحويل',

  // Urbanity
  IN_AGGLOMERATION: 'داخل التجمع العمراني',
  OUTSIDE_AGGLOMERATION: 'خارج التجمع العمراني',

  // Road sinuosity
  UNIQUE: 'مستقيم',
  RIGHT: 'منعطف يمين',
  LEFT: 'منعطف يسار',
  RIGHT_LEFT: 'يمين ثم يسار',
  LEFT_RIGHT: 'يسار ثم يمين',
  RIGHT_LEFT_RIGHT: 'يمين-يسار-يمين',
  LEFT_RIGHT_LEFT: 'يسار-يمين-يسار',

  // Road marking
  NONEXISTENT: 'غير موجود',
  LANE_SEPARATION: 'فصل بين الممرات',
  LANE_AND_EDGE: 'فصل وحافة',
  EDGE_ONLY: 'حافة فقط',

  // Plan layout
  STRAIGHT: 'مستقيم',
  GENTLE_CURVE: 'منحنى لطيف',
  DIFFICULT_CURVE_NO_SIGN: 'منحنى صعب بلا إشارة',
  DIFFICULT_CURVE_WITH_SIGN: 'منحنى صعب مع إشارة',

  // Road type
  TOLL_HIGHWAY: 'طريق سريع بالرسوم',
  FREE_HIGHWAY: 'طريق سريع مجاني',
  EXPRESS: 'طريق سريع',
  DUAL_CARRIAGEWAY: 'طريق مزدوج',
  CONVENTIONAL_2X1: 'طريق عادي 2×1',
  CONVENTIONAL_ADDITIONAL: 'طريق عادي إضافي',
  INTERCHANGE_RAMP: 'منحدر تبادل',
  CONTRAFLOW: 'تدفق معاكس',
  AGRICULTURAL: 'زراعي',
  SERVICE: 'طريق خدمة',
  OTHER: 'أخرى',

  // Network category
  HIGHWAY: 'طريق سريع',
  NATIONAL: 'وطني',
  REGIONAL: 'إقليمي',
  LOCAL: 'محلي',
  COMMUNAL: 'بلدي',
  UNCLASSIFIED: 'غير مصنف',

  // Traffic regime
  ONE_WAY: 'اتجاه واحد',
  BIDIRECTIONAL: 'ثنائي الاتجاه',
  SEPARATED: 'مفصول',
  VARIABLE: 'متغير',

  // Traffic direction
  INCREASING: 'تصاعدي',
  DECREASING: 'تنازلي',
  BOTH: 'كلا الاتجاهين',
  UNKNOWN: 'غير معروف',

  // Road width
  GREATER_375: 'أكثر من 3.75م',
  FROM_325_TO_375: 'من 3.25 إلى 3.75م',
  LESS_325: 'أقل من 3.25م',

  // Lane width
  LESS_6: 'أقل من 6م',
  FROM_6_TO_7: 'من 6 إلى 7م',
  GREATER_OR_EQUAL_7: '7م أو أكثر',

  // Luminosity
  FULL_DAYLIGHT: 'ضوء النهار الكامل',
  TWILIGHT_DAWN: 'الغسق / الفجر',
  NIGHT_NO_PUBLIC_LIGHTING: 'ليل بلا إضاءة عامة',
  NIGHT_LIGHTING_OFF: 'ليل والإضاءة مطفأة',
  NIGHT_LIGHTING_ON: 'ليل والإضاءة مضاءة',
  NIGHT_SUFFICIENT_LIGHTING: 'ليل وإضاءة كافية',
  INSUFFICIENT: 'ضوء غير كافٍ',

  // Atmospheric
  GOOD_WEATHER: 'طقس جيد',
  LIGHT_RAIN: 'مطر خفيف',
  HEAVY_RAIN: 'مطر غزير',
  FOG_SMOKE: 'ضباب / دخان',
  WIND: 'رياح',
  SNOW: 'ثلج',

  // Visibility
  CLEAR: 'واضحة',
  NOT_CLEAR: 'غير واضحة',
  FOG: 'ضباب',
  NIGHT: 'ليل',

  // Road pavement
  PAVED: 'معبد',
  UNPAVED: 'غير معبد',

  // Participant type
  DRIVER: 'سائق',
  PASSENGER: 'راكب',
  PEDESTRIAN: 'راجل',
  OWNER: 'مالك',
  WITNESS: 'شاهد',
  LEGAL_GUARDIAN: 'الولي القانوني',
  ESCORT: 'مرافق',
  DISPUTE_RESOLUTION_AGENT: 'عون تسوية النزاعات',
  COMPANION: 'مصاحب',

  // Vehicle type
  BICYCLE: 'دراجة هوائية',
  MOPED: 'دراجة نارية صغيرة',
  QUAD_50: 'رباعي 50 سم³',
  TRICYCLE: 'دراجة ثلاثية',
  MOTO_50_125: 'دراجة 50-125 سم³',
  MOTO_125: 'دراجة +125 سم³',
  QUAD_50_PLUS: 'رباعي +50 سم³',
  VEHICLE_ALONE: 'مركبة منفردة',
  VEHICLE_TRAILER: 'مركبة مع مقطورة',
  AGRICULTURAL_MACHINE: 'آلة زراعية',
  AGRICULTURAL_TRACTOR_NO_TRAILER: 'جرار زراعي بلا مقطورة',
  AGRICULTURAL_TRACTOR_TRAILER: 'جرار زراعي مع مقطورة',
  LIGHT_TRUCK_3_5T: 'شاحنة خفيفة ≤3.5ط',
  LIGHT_TRUCK_TRAILER: 'شاحنة خفيفة مع مقطورة',
  VAN: 'فان',
  PL_3_5_7_5T: 'شاحنة 3.5-7.5ط',
  PL_7_5T_PLUS: 'شاحنة +7.5ط',
  PL_TRAILER: 'شاحنة مع مقطورة',
  ROAD_TRACTOR_ALONE: 'جرار طرقي منفرد',
  ROAD_TRACTOR_SEMI_TRAILER: 'جرار طرقي مع نصف مقطورة',
  BUS_LINE: 'حافلة خط',
  BUS_OTHER: 'حافلة أخرى',
  TRAIN: 'قطار',
  LIGHT_METRO: 'مترو خفيف',
  TOWED_VEHICLE: 'مركبة مجرورة',
  PUSHED_VEHICLE: 'مركبة مدفوعة',
  CART: 'عربة',
  ANIMAL: 'حيوان',
  SPECIAL_EQUIPMENT: 'معدة خاصة',

  // Special type
  TAXI: 'تاكسي',
  LOUAGE: 'لواج',
  AMBULANCE: 'سيارة إسعاف',
  FIREFIGHTER: 'إطفاء',
  POLICE: 'شرطة',
  SCHOOL_TRANSPORT: 'نقل مدرسي',
  DANGEROUS_GOODS: 'بضائع خطرة',
  ROAD_MAINTENANCE: 'صيانة الطرق',
  NONE: 'لا شيء',

  // Insurance
  YES: 'نعم',
  NO: 'لا',
  NOT_PRESENT: 'غير موجود',

  // Vehicle position
  FRONT_LEFT: 'أمام يسار',
  FRONT_RIGHT: 'أمام يمين',
  REAR_LEFT: 'خلف يسار',
  REAR_RIGHT: 'خلف يمين',
  REAR_CENTER: 'خلف وسط',

  // Pedestrian location
  CROSSWALK: 'ممر المشاة',
  OUTSIDE_CROSSWALK: 'خارج ممر المشاة',
  SIDEWALK: 'رصيف',
  SHOULDER: 'كتف الطريق',

  // Action
  DRIVER_STRAIGHT: 'سائق مستقيم',
  DRIVER_TURN_LEFT: 'سائق يسار',
  DRIVER_TURN_RIGHT: 'سائق يمين',
  DRIVER_OVERTAKING: 'سائق يتجاوز',
  DRIVER_REVERSING: 'سائق يتراجع',
  DRIVER_STOPPING: 'سائق يتوقف',
  DRIVER_PARKING: 'سائق يركن',
  DRIVER_OTHER: 'سائق - أخرى',
  PEDESTRIAN_CROSSING: 'راجل يعبر',
  PEDESTRIAN_WALKING_SAME_DIRECTION: 'راجل في نفس الاتجاه',
  PEDESTRIAN_WALKING_OPPOSITE_DIRECTION: 'راجل في الاتجاه المعاكس',
  PEDESTRIAN_STANDING: 'راجل واقف',
  PEDESTRIAN_RUNNING: 'راجل يركض',
  PEDESTRIAN_OTHER: 'راجل - أخرى',

  // Travel reason
  HOME_WORK: 'من البيت للعمل',
  WORK_HOME: 'من العمل للبيت',
  PROFESSIONAL: 'مهني',
  SCHOOL: 'مدرسة',
  SHOPPING: 'تسوق',
  LEISURE: 'ترفيه',

  // Planned trip
  LESS_5KM: 'أقل من 5 كم',
  FROM_5_TO_25KM: 'من 5 إلى 25 كم',
  FROM_25_TO_50KM: 'من 25 إلى 50 كم',
  FROM_50_TO_100KM: 'من 50 إلى 100 كم',
  MORE_100KM: 'أكثر من 100 كم',

  // Safety equipment
  SEATBELT: 'حزام الأمان',
  HELMET: 'خوذة',
  CHILD_SEAT: 'مقعد أطفال',

  // Injury severity
  UNINJURED: 'غير مصاب',
  LIGHT_INJURY: 'إصابة خفيفة',
  SERIOUS_INJURY: 'إصابة خطيرة',
  FATAL: 'وفاة',

  // Test results
  NOT_DONE: 'لم يُجرَ',
  NEGATIVE: 'سلبي',
  POSITIVE: 'إيجابي',
  REFUSED: 'مرفوض',

  // Infraction
  SPEEDING: 'تجاوز السرعة',
  RED_LIGHT: 'تجاوز الضوء الأحمر',
  STOP_SIGN: 'عدم الوقوف عند اليافطة',
  WRONG_WAY: 'سير معاكس',
  NO_LICENSE: 'بلا رخصة',
  EXPIRED_LICENSE: 'رخصة منتهية',
  NO_INSURANCE: 'بلا تأمين',
  DUI: 'قيادة تحت التأثير',
  PHONE_USE: 'استخدام الهاتف',

  // Accident cause
  INATTENTION: 'عدم الانتباه',
  INAPPROPRIATE_SPEED: 'سرعة غير ملائمة',
  INFRACTION: 'مخالفة',
  INEXPERIENCE: 'قلة الخبرة',
  FATIGUE: 'تعب',
  ALCOHOL_DRUGS: 'كحول / مخدرات',
  ILLNESS: 'مرض',
  ROAD_CONDITION: 'حالة الطريق',
  SIGNAGE_CONDITION: 'حالة الإشارات',
  VEHICLE_CONDITION: 'حالة المركبة',
  BREAKDOWN: 'عطل',
  OVERLOAD: 'حمولة زائدة',
  ADVERSE_WEATHER: 'طقس سيء',
  GLARE: 'وهج',
  NO_OPINION: 'بدون رأي',

  // Accident type
  COLLISION_MOVING: 'تصادم بين مركبات متحركة',
  COLLISION_OBSTACLE: 'اصطدام بعائق',
  COLLISION_PEDESTRIAN_ANIMAL: 'اصطدام بمشاة / حيوان',
  ROLLOVER_ON_ROADWAY: 'انقلاب على الطريق',
  RUNOFF_LEFT_COLLISION: 'خروج يسار مع اصطدام',
  RUNOFF_RIGHT_COLLISION: 'خروج يمين مع اصطدام',
  RUNOFF_LEFT_NO_COLLISION: 'خروج يسار بلا اصطدام',
  RUNOFF_RIGHT_NO_COLLISION: 'خروج يمين بلا اصطدام',

  // Accident subtype
  FRONT: 'أمامي',
  REAR: 'خلفي',
  SIDE: 'جانبي',
  FRONT_SIDE: 'أمامي جانبي',
  CHAIN: 'تسلسلي',
  MULTIPLE: 'متعدد',
  PARKED_VEHICLE: 'مركبة متوقفة',
  SAFETY_BARRIER: 'حاجز أمان',
  LEVEL_CROSSING_BARRIER: 'حاجز عبور مستوى',
  SIGNAL_SUPPORT: 'عمود إشارة',
  ISLAND_REFUGE: 'جزيرة اللجوء',
  OTHER_OBJECT: 'جسم آخر',
  PEDESTRIAN_GROUP: 'مجموعة مشاة',
  PEDESTRIAN_BICYCLE: 'مشاة / دراجة',
  PEDESTRIAN_REPAIR: 'مشاة يُصلح',
  ANIMAL_DRIVER: 'حيوان سائق',
  ANIMAL_HERD: 'قطيع حيوانات',
  DOMESTIC_ANIMAL: 'حيوان أليف',
  WILD_ANIMAL: 'حيوان بري',
  LEFT_TREE: 'شجرة يسار',
  LEFT_POLE: 'عمود يسار',
  LEFT_BUILDING: 'مبنى يسار',
  LEFT_STREET_FURNITURE: 'أثاث حضري يسار',
  LEFT_CURB: 'حافة رصيف يسار',
  LEFT_DITCH: 'خندق يسار',
  LEFT_OTHER: 'يسار - أخرى',
  RIGHT_TREE: 'شجرة يمين',
  RIGHT_POLE: 'عمود يمين',
  RIGHT_BUILDING: 'مبنى يمين',
  RIGHT_STREET_FURNITURE: 'أثاث حضري يمين',
  RIGHT_CURB: 'حافة رصيف يمين',
  RIGHT_DITCH: 'خندق يمين',
  RIGHT_OTHER: 'يمين - أخرى',
  LEFT_FALL: 'سقوط يسار',
  LEFT_ROLLOVER: 'انقلاب يسار',
  LEFT_FLAT: 'انبطاح يسار',
  LEFT_OTHER_NO_COLLISION: 'يسار أخرى بلا اصطدام',
  RIGHT_FALL: 'سقوط يمين',
  RIGHT_ROLLOVER: 'انقلاب يمين',
  RIGHT_FLAT: 'انبطاح يمين',
  RIGHT_OTHER_NO_COLLISION: 'يمين أخرى بلا اصطدام',
  PASSENGER_FALL: 'سقوط راكب',
  VEHICLE_FIRE: 'حريق مركبة',
  COLLISION_TRAIN: 'اصطدام بقطار',
  COLLISION_METRO: 'اصطدام بمترو',
}

const fr: Record<string, string> = {
  WORKING: 'Jour ouvrable',
  BEFORE_HOLIDAY: 'Veille de fête',
  HOLIDAY: 'Jour férié',
  AFTER_HOLIDAY: 'Lendemain de fête',
  ON_ROAD: 'Sur la chaussée',
  ON_SHOULDER: "Sur l'accotement",
  ON_VERGE: "Sur l'herbe",
  ON_SIDEWALK: 'Sur le trottoir',
  ON_BIKE_PATH: 'Sur piste cyclable',
  ON_BIKE_LANE: 'Sur voie cyclable',
  OFF_PLATFORM: 'Hors plateforme',
  ROAD: 'Route',
  URBAN: 'Urbain',
  CROSSING: 'Carrefour',
  BYPASS: 'Déviation',
  IN_AGGLOMERATION: 'En agglomération',
  OUTSIDE_AGGLOMERATION: 'Hors agglomération',
  UNIQUE: 'Unique',
  RIGHT: 'À droite',
  LEFT: 'À gauche',
  RIGHT_LEFT: 'Droite-gauche',
  LEFT_RIGHT: 'Gauche-droite',
  RIGHT_LEFT_RIGHT: 'Droite-gauche-droite',
  LEFT_RIGHT_LEFT: 'Gauche-droite-gauche',
  NONEXISTENT: 'Inexistant',
  LANE_SEPARATION: 'Séparation de voies',
  LANE_AND_EDGE: 'Voie et rive',
  EDGE_ONLY: 'Rive uniquement',
  STRAIGHT: 'En ligne droite',
  GENTLE_CURVE: 'Courbe douce',
  DIFFICULT_CURVE_NO_SIGN: 'Courbe difficile sans signalisation',
  DIFFICULT_CURVE_WITH_SIGN: 'Courbe difficile avec signalisation',
  TOLL_HIGHWAY: 'Autoroute à péage',
  FREE_HIGHWAY: 'Autoroute gratuite',
  EXPRESS: 'Voie rapide',
  DUAL_CARRIAGEWAY: 'Route à chaussées séparées',
  CONVENTIONAL_2X1: 'Route 2×1 voie',
  CONVENTIONAL_ADDITIONAL: 'Route à voie supplémentaire',
  INTERCHANGE_RAMP: "Bretelle d'échangeur",
  CONTRAFLOW: 'Voie à contresens',
  AGRICULTURAL: 'Agricole',
  SERVICE: 'Voie de service',
  OTHER: 'Autre',
  HIGHWAY: 'Autoroute',
  NATIONAL: 'National',
  REGIONAL: 'Régional',
  LOCAL: 'Local',
  COMMUNAL: 'Communal',
  UNCLASSIFIED: 'Non classé',
  ONE_WAY: 'Sens unique',
  BIDIRECTIONAL: 'Bidirectionnel',
  SEPARATED: 'Séparé',
  VARIABLE: 'Variable',
  INCREASING: 'Croissant',
  DECREASING: 'Décroissant',
  BOTH: 'Les deux',
  UNKNOWN: 'Inconnu',
  GREATER_375: 'Plus de 3,75 m',
  FROM_325_TO_375: 'De 3,25 à 3,75 m',
  LESS_325: 'Moins de 3,25 m',
  LESS_6: 'Moins de 6 m',
  FROM_6_TO_7: 'De 6 à 7 m',
  GREATER_OR_EQUAL_7: '7 m ou plus',
  FULL_DAYLIGHT: 'Plein jour',
  TWILIGHT_DAWN: 'Crépuscule / aube',
  NIGHT_NO_PUBLIC_LIGHTING: 'Nuit sans éclairage public',
  NIGHT_LIGHTING_OFF: 'Nuit éclairage éteint',
  NIGHT_LIGHTING_ON: 'Nuit éclairage allumé',
  NIGHT_SUFFICIENT_LIGHTING: 'Nuit éclairage suffisant',
  INSUFFICIENT: 'Insuffisant',
  GOOD_WEATHER: 'Beau temps',
  LIGHT_RAIN: 'Pluie légère',
  HEAVY_RAIN: 'Pluie forte',
  FOG_SMOKE: 'Brouillard / fumée',
  WIND: 'Vent',
  SNOW: 'Neige',
  CLEAR: 'Claire',
  NOT_CLEAR: 'Réduite',
  FOG: 'Brouillard',
  NIGHT: 'Nuit',
  PAVED: 'Revêtu',
  UNPAVED: 'Non revêtu',
  DRIVER: 'Conducteur',
  PASSENGER: 'Passager',
  PEDESTRIAN: 'Piéton',
  OWNER: 'Propriétaire',
  WITNESS: 'Témoin',
  LEGAL_GUARDIAN: 'Tuteur légal',
  ESCORT: 'Escorte',
  DISPUTE_RESOLUTION_AGENT: 'Agent de résolution',
  COMPANION: 'Accompagnateur',
  BICYCLE: 'Vélo',
  MOPED: 'Cyclomoteur',
  QUAD_50: 'Quad 50 cc',
  TRICYCLE: 'Tricycle',
  MOTO_50_125: 'Moto 50-125 cc',
  MOTO_125: 'Moto +125 cc',
  QUAD_50_PLUS: 'Quad +50 cc',
  VEHICLE_ALONE: 'Voiture seule',
  VEHICLE_TRAILER: 'Voiture + remorque',
  AGRICULTURAL_MACHINE: 'Machine agricole',
  AGRICULTURAL_TRACTOR_NO_TRAILER: 'Tracteur agricole sans remorque',
  AGRICULTURAL_TRACTOR_TRAILER: 'Tracteur agricole + remorque',
  LIGHT_TRUCK_3_5T: 'Camionnette ≤3,5 t',
  LIGHT_TRUCK_TRAILER: 'Camionnette + remorque',
  VAN: 'Fourgon',
  PL_3_5_7_5T: 'PL 3,5-7,5 t',
  PL_7_5T_PLUS: 'PL +7,5 t',
  PL_TRAILER: 'PL + remorque',
  ROAD_TRACTOR_ALONE: 'Tracteur routier seul',
  ROAD_TRACTOR_SEMI_TRAILER: 'Tracteur + semi-remorque',
  BUS_LINE: 'Autobus de ligne',
  BUS_OTHER: 'Autre autobus',
  TRAIN: 'Train',
  LIGHT_METRO: 'Métro léger',
  TOWED_VEHICLE: 'Véhicule remorqué',
  PUSHED_VEHICLE: 'Véhicule poussé',
  CART: 'Charrette',
  ANIMAL: 'Animal',
  SPECIAL_EQUIPMENT: 'Engin spécial',
  TAXI: 'Taxi',
  LOUAGE: 'Louage',
  AMBULANCE: 'Ambulance',
  FIREFIGHTER: 'Pompier',
  POLICE: 'Police',
  SCHOOL_TRANSPORT: 'Transport scolaire',
  DANGEROUS_GOODS: 'Matières dangereuses',
  ROAD_MAINTENANCE: 'Maintenance routière',
  NONE: 'Aucun',
  YES: 'Oui',
  NO: 'Non',
  NOT_PRESENT: 'Non présente',
  FRONT_LEFT: 'Avant gauche',
  FRONT_RIGHT: 'Avant droit',
  REAR_LEFT: 'Arrière gauche',
  REAR_RIGHT: 'Arrière droit',
  REAR_CENTER: 'Arrière centre',
  CROSSWALK: 'Passage piéton',
  OUTSIDE_CROSSWALK: 'Hors passage piéton',
  SIDEWALK: 'Trottoir',
  SHOULDER: 'Accotement',
  DRIVER_STRAIGHT: 'Conducteur tout droit',
  DRIVER_TURN_LEFT: 'Conducteur tourne à gauche',
  DRIVER_TURN_RIGHT: 'Conducteur tourne à droite',
  DRIVER_OVERTAKING: 'Conducteur en dépassement',
  DRIVER_REVERSING: 'Conducteur en marche arrière',
  DRIVER_STOPPING: "Conducteur s'arrête",
  DRIVER_PARKING: 'Conducteur se gare',
  DRIVER_OTHER: 'Conducteur autre',
  PEDESTRIAN_CROSSING: 'Piéton traverse',
  PEDESTRIAN_WALKING_SAME_DIRECTION: 'Piéton même sens',
  PEDESTRIAN_WALKING_OPPOSITE_DIRECTION: 'Piéton sens inverse',
  PEDESTRIAN_STANDING: 'Piéton immobile',
  PEDESTRIAN_RUNNING: 'Piéton court',
  PEDESTRIAN_OTHER: 'Piéton autre',
  HOME_WORK: 'Domicile-travail',
  WORK_HOME: 'Travail-domicile',
  PROFESSIONAL: 'Professionnel',
  SCHOOL: 'École',
  SHOPPING: 'Courses',
  LEISURE: 'Loisirs',
  LESS_5KM: 'Moins de 5 km',
  FROM_5_TO_25KM: 'De 5 à 25 km',
  FROM_25_TO_50KM: 'De 25 à 50 km',
  FROM_50_TO_100KM: 'De 50 à 100 km',
  MORE_100KM: 'Plus de 100 km',
  SEATBELT: 'Ceinture de sécurité',
  HELMET: 'Casque',
  CHILD_SEAT: 'Siège enfant',
  UNINJURED: 'Indemne',
  LIGHT_INJURY: 'Blessé léger',
  SERIOUS_INJURY: 'Blessé grave',
  FATAL: 'Tué',
  NOT_DONE: 'Non effectué',
  NEGATIVE: 'Négatif',
  POSITIVE: 'Positif',
  REFUSED: 'Refusé',
  SPEEDING: 'Excès de vitesse',
  RED_LIGHT: 'Feu rouge grillé',
  STOP_SIGN: 'Stop non respecté',
  WRONG_WAY: 'Sens interdit',
  NO_LICENSE: 'Sans permis',
  EXPIRED_LICENSE: 'Permis expiré',
  NO_INSURANCE: 'Sans assurance',
  DUI: 'Conduite sous influence',
  PHONE_USE: 'Usage du téléphone',
  INATTENTION: 'Inattention',
  INAPPROPRIATE_SPEED: 'Vitesse inadaptée',
  INFRACTION: 'Infraction',
  INEXPERIENCE: 'Inexpérience',
  FATIGUE: 'Fatigue',
  ALCOHOL_DRUGS: 'Alcool / stupéfiants',
  ILLNESS: 'Maladie',
  ROAD_CONDITION: 'État de la route',
  SIGNAGE_CONDITION: 'État de la signalisation',
  VEHICLE_CONDITION: 'État du véhicule',
  BREAKDOWN: 'Panne',
  OVERLOAD: 'Surcharge',
  ADVERSE_WEATHER: 'Intempéries',
  GLARE: 'Éblouissement',
  NO_OPINION: 'Sans avis',
  COLLISION_MOVING: 'Collision entre véhicules en mouvement',
  COLLISION_OBSTACLE: 'Collision avec obstacle',
  COLLISION_PEDESTRIAN_ANIMAL: 'Collision piéton / animal',
  ROLLOVER_ON_ROADWAY: 'Renversement sur chaussée',
  RUNOFF_LEFT_COLLISION: 'Sortie gauche avec collision',
  RUNOFF_RIGHT_COLLISION: 'Sortie droite avec collision',
  RUNOFF_LEFT_NO_COLLISION: 'Sortie gauche sans collision',
  RUNOFF_RIGHT_NO_COLLISION: 'Sortie droite sans collision',
  FRONT: 'Frontal',
  REAR: "Par l'arrière",
  SIDE: 'Latéral',
  FRONT_SIDE: 'Frontal-latéral',
  CHAIN: 'En chaîne',
  MULTIPLE: 'Multiple',
  PARKED_VEHICLE: 'Véhicule en stationnement',
  SAFETY_BARRIER: 'Glissière de sécurité',
  LEVEL_CROSSING_BARRIER: 'Barrière passage à niveau',
  SIGNAL_SUPPORT: 'Support de signalisation',
  ISLAND_REFUGE: 'Îlot refuge',
  OTHER_OBJECT: 'Autre objet',
  PEDESTRIAN_GROUP: 'Groupe de piétons',
  PEDESTRIAN_BICYCLE: 'Piéton / vélo',
  PEDESTRIAN_REPAIR: 'Piéton en réparation',
  ANIMAL_DRIVER: 'Animal conducteur',
  ANIMAL_HERD: 'Troupeau',
  DOMESTIC_ANIMAL: 'Animal domestique',
  WILD_ANIMAL: 'Animal sauvage',
  LEFT_TREE: 'Arbre gauche',
  LEFT_POLE: 'Poteau gauche',
  LEFT_BUILDING: 'Bâtiment gauche',
  LEFT_STREET_FURNITURE: 'Mobilier urbain gauche',
  LEFT_CURB: 'Bordure gauche',
  LEFT_DITCH: 'Fossé gauche',
  LEFT_OTHER: 'Gauche autre',
  RIGHT_TREE: 'Arbre droit',
  RIGHT_POLE: 'Poteau droit',
  RIGHT_BUILDING: 'Bâtiment droit',
  RIGHT_STREET_FURNITURE: 'Mobilier urbain droit',
  RIGHT_CURB: 'Bordure droite',
  RIGHT_DITCH: 'Fossé droit',
  RIGHT_OTHER: 'Droite autre',
  LEFT_FALL: 'Chute gauche',
  LEFT_ROLLOVER: 'Renversement gauche',
  LEFT_FLAT: 'À plat gauche',
  LEFT_OTHER_NO_COLLISION: 'Gauche autre sans collision',
  RIGHT_FALL: 'Chute droite',
  RIGHT_ROLLOVER: 'Renversement droit',
  RIGHT_FLAT: 'À plat droit',
  RIGHT_OTHER_NO_COLLISION: 'Droite autre sans collision',
  PASSENGER_FALL: 'Chute passager',
  VEHICLE_FIRE: 'Incendie véhicule',
  COLLISION_TRAIN: 'Collision train',
  COLLISION_METRO: 'Collision métro',
}

const maps: Record<string, Record<string, string>> = { ar, fr }

export function getEnumLabel(value: string, locale: string, fallback: (v: string) => string): string {
  const map = maps[locale]
  if (map && Object.prototype.hasOwnProperty.call(map, value)) return map[value]
  return fallback(value)
}
